language: python
python: 2.7

python:
    - TOX_ENV=docs
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - tox -e $TOX_ENV
    - coverage run --source=roz setup.py test

branches:
  only:
    - experimental

after_success:
     coveralls --verbose